# Generated by Django 4.1.5 on 2023-01-31 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_helmetmodels'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='Sellerlogo/')),
                ('proof', models.FileField(upload_to='Sellerproof/')),
                ('password', models.CharField(max_length=50)),
                ('doj', models.DateField(auto_now=True)),
                ('vstatus', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
