# Generated by Django 4.1.5 on 2023-02-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_admintable'),
        ('Guest', '0004_alter_newuser_password_alter_seller_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delevery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='DeleveryDocs/')),
                ('password', models.CharField(max_length=50, unique=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.seller')),
            ],
        ),
    ]
