# Generated by Django 4.1.5 on 2023-02-06 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_admintable'),
        ('Guest', '0004_alter_newuser_password_alter_seller_password'),
        ('Seller', '0003_delevery_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='productt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('details', models.EmailField(max_length=100)),
                ('photo', models.FileField(upload_to='productDocs/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.helmetmodels')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.seller')),
            ],
        ),
    ]
