# Generated by Django 4.1.5 on 2023-02-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_workassign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workassign',
        ),
    ]
