# Generated by Django 4.1.5 on 2023-04-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0012_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('details', models.EmailField(max_length=100)),
            ],
        ),
    ]
