# Generated by Django 4.1.5 on 2023-01-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Models',
        ),
    ]
