# Generated by Django 4.1.5 on 2023-02-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_complaint_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
