# Generated by Django 4.1.5 on 2023-02-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_complaint_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='seller',
        ),
    ]
