# Generated by Django 4.1.5 on 2023-02-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_complaint_seller_remove_feedback_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
