# Generated by Django 4.1.5 on 2023-02-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_complaint_seller_feedback_seller_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_replay',
            field=models.CharField(default='not viewed yet', max_length=99),
        ),
    ]
